# Start databases (dependencies of backend) - backend database, and example postgres and mysql databases

services:
  # Postgres database used by backend
  noql-postgres:
    image: postgres:16-alpine
    container_name: noql-postgres-database-stack
    ports:
      - "5432:5432"
    volumes:
      - ./stack-data/database-stack/backend-database-data:/var/lib/postgresql/data
    env_file:
      - ../../backend/.env.local

  # Example data source that can be connected to backend
  postgres:
    image: postgres:16-alpine
    container_name: example-postgres-database-stack
    ports:
      - "5433:5432"
    volumes:
      - ./stack-data/database-stack/example-postgres-data:/var/lib/postgresql/data
      - ./sample-data.sql:/sample-data.sql
    env_file:
      - ../../backend/.env.local

  # Example data source that can be connected to backend
  mysql:
    image: mysql:8.4.0
    container_name: example-mysql-database-stack
    ports:
      - "3306:3306"
    volumes:
      - ./stack-data/database-stack/example-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  # Plot service is isolated environment for running python scripts that generate plots
  plot-service:
    image: janbabak/noql-plot-service:0.0.1
    container_name: plot-service-database-stack
    tty: true
    stdin_open: true
    volumes:
      - ../../plotService:/app/plotService
