name: Build backend

on:
  workflow_call:
    inputs:
      push_docker:
        required: false
        type: boolean
        default: false
    secrets:
      DOCKERHUB_USERNAME:
        description: 'Docker Hub username for login'
        required: true
      DOCKERHUB_TOKEN:
        description: 'Docker Hub access token for login'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: experimental
        run: echo "hello"
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('backend/**.gradle*', 'backend/**/gradle-wrapper.properties') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run tests with coverage
        working-directory: backend
        run: ./gradlew test jacocoTestReport

      - name: Summary setup
        run: echo "# ðŸ§ª Test Results:" >> $GITHUB_STEP_SUMMARY

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "backend/build/test-results/test/TEST-*.xml"
        if: always()

      - name: Coverage Summary
        if: always()
        working-directory: backend
        run: |
          TOTAL_COVERAGE=$(./gradlew computeTotalTestCoverage -q)
          echo "Total test coverage ${TOTAL_COVERAGE}%"
          echo "coverage=$TOTAL_COVERAGE%" >> $GITHUB_OUTPUT
          echo "**Total Coverage:** ${TOTAL_COVERAGE}%" >> $GITHUB_STEP_SUMMARY

      - name: Build backend
        working-directory: backend
        run: ./gradlew build

      - name: Login to Docker Hub
        if: inputs.push_docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: inputs.push_docker
        uses: docker/setup-buildx-action@v3
        with:
          name: backend-builder

      - name: Build & push Docker image
        if: inputs.push_docker
        working-directory: backend
        run: ./gradlew dockerBuildBackend