name: Build Plot service

on:
  workflow_dispatch:

jobs:
  validate-backend-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Fetch main branch
        run: git fetch origin main

      # If plot service changes aren't detected, don't validate plot service version increase
      - name: Detect backend changes
        id: plot_service_changes
        run: |
          if git diff --name-only main ${{ github.sha }} | grep -q '^backend/docker/plotService.Dockerfile'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Get current plot service version
        if: steps.plot_service_changes.outputs.changed == 'true'
        id: pr_version
        run: |
          PR_VERSION=$(grep '^[[:space:]]*plotServiceVersion:' backend/build.gradle \
            | awk -F: '{gsub(/[ '\'',]/,"",$2); print $2}')
          echo "PR_VERSION=$PR_VERSION" >> $GITHUB_OUTPUT

      - name: Get main plot service version
        if: steps.plot_service_changes.outputs.changed == 'true'
        id: main_version
        run: |
          MAIN_VERSION=$(git show origin/main:backend/build.gradle \
            | grep '^[[:space:]]*plotServiceVersion:' backend/build.gradle \
            | awk -F: '{gsub(/[ '\'',]/,"",$2); print $2}')
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_OUTPUT

      - name: Check semantic version increment
        if: steps.plot_service_changes.outputs.changed == 'true'
        run: |
          ./ci/scripts/check-semantic-versioning.sh \
            "${{ steps.pr_version.outputs.PR_VERSION }}" \
            "${{ steps.main_version.outputs.MAIN_VERSION }}"

  build-plotservice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-plotservice-${{ hashFiles('backend/**.gradle*', 'backend/**/gradle-wrapper.properties') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          name: plotservice-builder

      - name: Build & push Docker image
        working-directory: backend
        run: ./gradlew dockerBuildPlotService