name: Plot service pipeline

on:
  push:
    branches-ignore:
      - main
      - master
  workflow_dispatch:

jobs:
  validate-plot-service:
    uses: janbabak/NoQL/.github/workflows/plotservice-validate.yaml@main

  build-plot-service:
    needs: validate-plot-service
    if: |
      needs.validate-plot-service.outputs.plot_service_changed == 'true' ||
      github.event_name == 'workflow_dispatch'
    uses: janbabak/NoQL/.github/workflows/plotservice-build.yaml@main
    with:
      push_docker: ${{ github.event_name == 'workflow_dispatch' }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}