name: Validate plot service

on:
  workflow_call:
    outputs:
      plot_service_changed:
        description: 'True if plot service code has changed on this branch.'
        value: ${{ jobs.detect-changes.outputs.plot_service_changed }}

jobs:
  # Detect changes in the /backend folder (ignoring /backend/docker/plotService.Dockerfile)
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      plot_service_changed: ${{ steps.detect.outputs.changed }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Fetch main branch
        run: git fetch origin main

      # If plot service changes aren't detected, don't validate plot service version increase
      - name: Detect plot service changes
        id: detect
        run: |
          if git diff --name-only origin/main ${{ github.sha }} | grep -q '^backend/docker/plotService.Dockerfile'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  # Validate plot service version has been increased when plot service changes have been detected
  validate-version:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.plot_service_changed == 'true'

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get main plot service version
        id: main_version
        run: |
          MAIN_VERSION=$(git show origin/main:backend/build.gradle \
            | grep '^[[:space:]]*plotServiceVersion:' \
            | awk -F: '{gsub(/[ '\'',]/,"",$2); print $2}')
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_OUTPUT

      - name: Check semantic version increment
        run: |
          ./ci/scripts/check-semantic-versioning.sh \
            "${{ steps.pr_version.outputs.PR_VERSION }}" \
            "${{ steps.main_version.outputs.MAIN_VERSION }}"

      - name: Check semantic version increment
        run: |
          ./ci/scripts/check-semantic-versioning.sh \
            "${{ steps.pr_version.outputs.PR_VERSION }}" \
            "${{ steps.main_version.outputs.MAIN_VERSION }}"